kind: pipeline
type: docker
name: Mimir App Pipeline

steps:
  - name: build
    image: enonic/enonic-ci:7.1-node
    commands:
      - /setup_sandbox.sh
      - npm install
      - npm run gulp
      - enonic project build
  - name: Deploy to test
    image: enonic/enonic-ci:7.1-node
    environment:
      ENONIC_CLI_REMOTE_URL:
        from_secret: ssb-xp7t-url
      ENONIC_CLI_REMOTE_USER:
        from_secret: ssb-xp7t-user
      ENONIC_CLI_REMOTE_PASS:
        from_secret: ssb-xp7t-pass
    commands:
      - enonic app install --file build/libs/*.jar
#    when:
#      branch:
#        - master
#    depends_on:
#      - build
