name: 'Manual deploy to PROD'
# Action that will download previously created artifact and deploy it to the production environment
on:
  workflow_dispatch:
   # We need the Github Action Run number to select which artifact to download
    inputs:
      gh_run_number:
        description: 'The Github Action run number to deploy'
        required: true

jobs:
  deploy-artifact:
    name: 'Deploy artifact'
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: mimir-test-${{ github.event.inputs.gh_run_number }}
      - name: display downloads
        run: ls -R