name: 'Manual deploy to TEST'
# Action that will download previously created artifact and deploy it to the production environment
on:
  workflow_dispatch:
   # We need the Github Action Run number to select which artifact to download
    inputs:
      gh_run_number:
        description: 'The Github Action run number to deploy'
        required: true

jobs:
  deploy-artifact:
    name: 'Deploy artifact'
    runs-on: ubuntu-latest
    steps:
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.23.0
        with:
          workflow: deploy_to_test.yaml
          run_number: ${{ github.event.inputs.gh_run_number }}
      - name: display downloads
        run: ls -R
